cc_library(
    visibility = ["//visibility:public"],
    name = "ascii",
    hdrs = glob(["*.hh"]),
    srcs = glob(["*.cc"]),
    includes = [""],
    deps = [
        "//thirdparty/nanosvg",
    ]
)
